title: Isaac Pollack
author: Isaac Pollack
url: https://isaac-pollack.github.io/ # root address of the site
description: > # description of the site (multiple lines allowed)
  My portfolio website, created using Jekyll, Github Pages and a little bit of the ol' noggin.
  All projects can be found on the github link at the bottom of this page.

permalink: /:slug

favicon: "./assets/images/favicon/favicon.ico" # relative path to site's favicon

twitter:
    username: Isaac_Pollack # update or delete this
    card: summary_large_image

remote_theme: abhinavs/moonwalk

theme_config:
  appearance: "dark" # can be "light", "dark" or "auto"
  appearance_toggle: true # if appearance can be switched by user
  back_home_text: "home.." # customize text for homepage link in post layout
  date_format: "%d-%m-%Y" # customize how date is formatted
  show_description: true # show blog description
  show_navbar: true # show horizontal navbar
  show_footer: true # show footer links in home page,add in _data/home.yml
  # following keys are using to create home layout
  show_projects: true # show projects as cards, add in _data/home.yml
  show_blog: false
  show_misc_list: false # show generic vertical list for misc details, add _data/home.yml
  show_reading_time: false # show number of words and reading time in the blog posts
  show_tags: true # show tags in a blog posts
  # options for "home" page
  home:
    title_projects: Portfolio
    title_misc_list: Details

highlighter: rouge

sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
